name: Run shellcheck on any shell files
run-name: ${{ github.actor }} is checking all shell files🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
          - run: find ${{ github.workspace }} -name '*.sh' -type f -exec shellcheck {} \;
